name: Test & Publish
on:
  push:
    branches:
    - master

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test # will run `yarn test` command
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command
    - name: clone cappyzawa.github.io
      uses: actions/checkout@v2
      with:
        repository: cappyzawa/cappyzawa.github.io
        ssh-key: ${{ secrets.PRIVATE_KEY }}
    - run: |
        ls -al ../
    - run: |
        git config --local user.name cappyzawa
        git config --local user.email cappyzawa@gmail.com

        # git add elm.js
        # git commit -m "[ci skip] BUILD by bot" --allow-empty
        #
        # git remote set-url origin https://cappyzawa:${GITHUB_TOKEN}@github.com/cappyzawa/cappyzawa.github.io
        # git push origin master
