name: Test & Publish
on:
  push:
    branches:
    - master

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: test
      uses: nuxt/actions-yarn@master
      with:
        args: test
    - name: Codecov Action
      uses: Atrox/codecov-action@v0.1.3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: build
      uses: nuxt/actions-yarn@master
      with:
        args: run build
    - name: clone cappyzawa.github.io
      run: |
        git clone https://github.com/cappyzawa/cappyzawa.github.io.git ../cappyzawa.github.io
        mv elm.js ../cappyzawa.github.io/
    - name: commit & publish
      run: |
        cd ../cappyzawa.github.io

        git config --local user.name cappyzawa
        git config --local user.email cappyzawa@yahoo.ne.jp

        git add elm.js
        git commit -m "[ci skip] BUILD by bot" --allow-empty

        git remote set-url origin https://cappyzawa:${GITHUB_TOKEN}@github.com/cappyzawa/cappyzawa.github.io
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
