name: Test & Publish
on: [push]

jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: test
      uses: nuxt/actions-yarn@master
      with:
        args: test
    - name: Codecov Action
      uses: Atrox/codecov-action@v0.1.3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install
      uses: nuxt/actions-yarn@master
      with:
        args: install
    - name: build
      uses: nuxt/actions-yarn@master
      with:
        args: run build
    - run: git config --local user.name=cappyzawa
    - run: git config --local user.email=cappyzawa@yahoo.ne.jp
    - run: git config --local user.password=${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
